[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
  "@chainlink/contracts/=lib/chainlink/contracts/",
  "@chainlink/contracts-ccip/=lib/chainlink-ccip/"
]

# Somnia Testnet configuration
[rpc_endpoints]
somnia_mainnet = "https://dream-rpc.somnia.network"

[etherscan]
somnia_mainnet = { key = "anything", url = "https://shannon-explorer.somnia.network/api" }

# Somnia Mainnet configuration
[profile.sonic-mainnet]
somnia_mainnet_rpc_url = "https://dream-rpc.somnia.network/"
chain_id = 146

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
